[package]
name = "shingles"
version = "0.1.0"
authors = ["Dmitriy <dimack@gmail.com>"]
description = "Shingles implementation in rust"
keywords = ["shingle", "ngram", "fuzzy"]
exclude = [".*"]

[dependencies]
